<?php defined( 'ABSPATH' ) OR die( 'This script cannot be accessed directly.' );

return array(

	'cl-flipbox' => array(
		'base' => 'cl-flipbox',
		'name' => __( 'FlipBox', 'codelights' ),
		'description' => __( 'Two-sided content element, flipping on hover', 'codelights' ),
		'class' => '',
		'weight' => 200,
		'category' => 'CodeLights',
		'icon' => 'flipbox',
		'params' => array(
			/**
			 * Front Side
			 */
			array(
				'param_name' => 'front_icon',
				'heading' => __( 'Icon', 'codelights' ),
				'type' => 'textfield',
				'group' => __( 'Front Side', 'codelights' ),
				'weight' => 310,
			),
			array(
				'param_name' => 'front_icon_style',
				'heading' => __( 'Icon Style', 'codelights' ),
				'type' => 'dropdown',
				'value' => array(
					__( 'Simple', 'codelights' ) => 'default',
					__( 'Inside the Solid circle', 'codelights' ) => 'circle',
				),
				'edit_field_class' => 'vc_col-sm-6 vc_column',
				'dependency' => array( 'element' => 'front_icon', 'not_empty' => TRUE ),
				'group' => __( 'Front Side', 'codelights' ),
				'weight' => 300,
			),
			array(
				'param_name' => 'front_icon_size',
				'heading' => __( 'Icon Style', 'codelights' ),
				'type' => 'dropdown',
				'value' => array(
					__( 'Extra-Small', 'codelights' ) => 'xs',
					__( 'Small', 'codelights' ) => 's',
					__( 'Medium', 'codelights' ) => 'm',
					__( 'Large', 'codelights' ) => 'l',
					__( 'Extra-Large', 'codelights' ) => 'xl',
				),
				'std' => 'm',
				'edit_field_class' => 'vc_col-sm-6 vc_column',
				'dependency' => array( 'element' => 'front_icon', 'not_empty' => TRUE ),
				'group' => __( 'Front Side', 'codelights' ),
				'weight' => 290,
			),
			array(
				'param_name' => 'front_icon_color',
				'heading' => __( 'Icon Color', 'codelights' ),
				'type' => 'colorpicker',
				'edit_field_class' => 'vc_col-sm-6 vc_column',
				'dependency' => array( 'element' => 'front_icon', 'not_empty' => TRUE ),
				'group' => __( 'Front Side', 'codelights' ),
				'weight' => 280,
			),
			array(
				'param_name' => 'front_icon_bgcolor',
				'heading' => __( 'Icon Background', 'codelights' ),
				'type' => 'colorpicker',
				'edit_field_class' => 'vc_col-sm-6 vc_column',
				'dependency' => array( 'element' => 'front_icon', 'not_empty' => TRUE ),
				'group' => __( 'Front Side', 'codelights' ),
				'weight' => 270,
			),
			array(
				'param_name' => 'front_image',
				'heading' => __( 'Image', 'codelights' ),
				'type' => 'attach_image',
				'group' => __( 'Front Side', 'codelights' ),
				'weight' => 260,
			),
			array(
				'param_name' => 'front_title',
				'heading' => __( 'Heading', 'codelights' ),
				'type' => 'textfield',
				'admin_label' => TRUE,
				'group' => __( 'Front Side', 'codelights' ),
				'weight' => 250,
			),
			array(
				'param_name' => 'front_text',
				'heading' => __( 'Text', 'codelights' ),
				'type' => 'textarea',
				'group' => __( 'Front Side', 'codelights' ),
				'weight' => 240,
			),
			array(
				'param_name' => 'front_bgcolor',
				'heading' => __( 'Background Color', 'codelights' ),
				'type' => 'colorpicker',
				'group' => __( 'Front Side', 'codelights' ),
				'weight' => 230,
			),
			array(
				'param_name' => 'front_border_style',
				'heading' => __( 'Border Style', 'codelights' ),
				'type' => 'dropdown',
				'value' => array(
					__( 'None', 'codelights' ) => 'none',
					__( 'Dotted', 'codelights' ) => 'dotted',
					__( 'Dashed', 'codelights' ) => 'dashed',
					__( 'Solid', 'codelights' ) => 'solid',
					__( 'Double', 'codelights' ) => 'double',
				),
				'group' => __( 'Front Side', 'codelights' ),
				'weight' => 220,
			),
			array(
				'param_name' => 'front_border_color',
				'heading' => __( 'Border Color', 'codelights' ),
				'type' => 'colorpicker',
				'edit_field_class' => 'vc_col-sm-6 vc_column',
				'dependency' => array(
					'element' => 'front_border_style',
					'value' => array( 'dotted', 'dashed', 'solid', 'double' ),
				),
				'group' => __( 'Front Side', 'codelights' ),
				'weight' => 210,
			),
			array(
				'param_name' => 'front_border_size',
				'heading' => __( 'Border Size', 'codelights' ),
				'type' => 'dropdown',
				'value' => array(
					sprintf( __( '%dpx', 'codelights' ), 1 ) => '1px',
					sprintf( __( '%dpx', 'codelights' ), 2 ) => '2px',
					sprintf( __( '%dpx', 'codelights' ), 3 ) => '3px',
					sprintf( __( '%dpx', 'codelights' ), 4 ) => '4px',
					sprintf( __( '%dpx', 'codelights' ), 5 ) => '5px',
					sprintf( __( '%dpx', 'codelights' ), 6 ) => '6px',
					sprintf( __( '%dpx', 'codelights' ), 7 ) => '7px',
					sprintf( __( '%dpx', 'codelights' ), 8 ) => '8px',
					sprintf( __( '%dpx', 'codelights' ), 9 ) => '9px',
				),
				'std' => '1px',
				'edit_field_class' => 'vc_col-sm-6 vc_column',
				'dependency' => array(
					'element' => 'front_border_style',
					'value' => array( 'dotted', 'dashed', 'solid', 'double' ),
				),
				'group' => __( 'Front Side', 'codelights' ),
				'weight' => 200,
			),
			/**
			 * Back Side
			 */
			array(
				'param_name' => 'back_image',
				'heading' => __( 'Image', 'codelights' ),
				'type' => 'attach_image',
				'group' => __( 'Back Side', 'codelights' ),
				'weight' => 190,
			),
			array(
				'param_name' => 'back_title',
				'heading' => __( 'Heading', 'codelights' ),
				'type' => 'textfield',
				'group' => __( 'Back Side', 'codelights' ),
				'weight' => 180,
			),
			array(
				'param_name' => 'back_text',
				'heading' => __( 'Text', 'codelights' ),
				'type' => 'textarea',
				'group' => __( 'Back Side', 'codelights' ),
				'weight' => 170,
			),
			array(
				'param_name' => 'back_button_label',
				'heading' => __( 'Button Label', 'codelights' ),
				'type' => 'textfield',
				'edit_field_class' => 'vc_col-sm-6 vc_column',
				'group' => __( 'Back Side', 'codelights' ),
				'weight' => 160,
			),
			array(
				'param_name' => 'back_button_size',
				'heading' => __( 'Button Label', 'codelights' ),
				'type' => 'dropdown',
				'value' => array(
					__( 'Extra-Small', 'codelights' ) => 'xs',
					__( 'Small', 'codelights' ) => 's',
					__( 'Medium', 'codelights' ) => 'm',
					__( 'Large', 'codelights' ) => 'l',
					__( 'Extra-Large', 'codelights' ) => 'xl',
				),
				'std' => 'm',
				'edit_field_class' => 'vc_col-sm-6 vc_column',
				'group' => __( 'Back Side', 'codelights' ),
				'weight' => 150,
			),
			array(
				'param_name' => 'back_button_label',
				'heading' => __( 'Button Text Color', 'codelights' ),
				'type' => 'colorpicker',
				'edit_field_class' => 'vc_col-sm-6 vc_column',
				'group' => __( 'Back Side', 'codelights' ),
				'weight' => 140,
			),
			array(
				'param_name' => 'back_button_bgcolor',
				'heading' => __( 'Button Background Color', 'codelights' ),
				'type' => 'colorpicker',
				'edit_field_class' => 'vc_col-sm-6 vc_column',
				'group' => __( 'Back Side', 'codelights' ),
				'weight' => 130,
			),
			array(
				'param_name' => 'back_bgcolor',
				'heading' => __( 'Background Color', 'codelights' ),
				'type' => 'colorpicker',
				'group' => __( 'Back Side', 'codelights' ),
				'weight' => 120,
			),
			array(
				'param_name' => 'back_border_style',
				'heading' => __( 'Border Style', 'codelights' ),
				'type' => 'dropdown',
				'value' => array(
					__( 'None', 'codelights' ) => 'none',
					__( 'Dotted', 'codelights' ) => 'dotted',
					__( 'Dashed', 'codelights' ) => 'dashed',
					__( 'Solid', 'codelights' ) => 'solid',
					__( 'Double', 'codelights' ) => 'double',
				),
				'group' => __( 'Back Side', 'codelights' ),
				'weight' => 110,
			),
			array(
				'param_name' => 'back_border_color',
				'heading' => __( 'Border Color', 'codelights' ),
				'type' => 'colorpicker',
				'edit_field_class' => 'vc_col-sm-6 vc_column',
				'dependency' => array(
					'element' => 'back_border_style',
					'value' => array( 'dotted', 'dashed', 'solid', 'double' ),
				),
				'group' => __( 'Back Side', 'codelights' ),
				'weight' => 100,
			),
			array(
				'param_name' => 'back_border_size',
				'heading' => __( 'Border Size', 'codelights' ),
				'type' => 'dropdown',
				'value' => array(
					sprintf( __( '%dpx', 'codelights' ), 1 ) => '1px',
					sprintf( __( '%dpx', 'codelights' ), 2 ) => '2px',
					sprintf( __( '%dpx', 'codelights' ), 3 ) => '3px',
					sprintf( __( '%dpx', 'codelights' ), 4 ) => '4px',
					sprintf( __( '%dpx', 'codelights' ), 5 ) => '5px',
					sprintf( __( '%dpx', 'codelights' ), 6 ) => '6px',
					sprintf( __( '%dpx', 'codelights' ), 7 ) => '7px',
					sprintf( __( '%dpx', 'codelights' ), 8 ) => '8px',
					sprintf( __( '%dpx', 'codelights' ), 9 ) => '9px',
				),
				'std' => '1px',
				'edit_field_class' => 'vc_col-sm-6 vc_column',
				'dependency' => array(
					'element' => 'back_border_style',
					'value' => array( 'dotted', 'dashed', 'solid', 'double' ),
				),
				'group' => __( 'Back Side', 'codelights' ),
				'weight' => 90,
			),
			/**
			 * Animation
			 */
			array(
				'param_name' => 'animation',
				'heading' => __( 'Animation Type', 'codelights' ),
				'type' => 'dropdown',
				'value' => array(
					__( 'Card Flip', 'codelights' ) => 'cardflip',
					__( 'Cube Sides', 'codelights' ) => 'cubesides',
					__( 'Empty Box', 'codelights' ) => 'emptybox',
					__( 'Cover Open', 'codelights' ) => 'coveropen',
				),
				'group' => __( 'Animation', 'codelights' ),
				'weight' => 80,
			),
			array(
				'param_name' => 'direction',
				'heading' => __( 'Animation Direction', 'codelights' ),
				'type' => 'dropdown',
				'value' => array(
					__( 'North', 'codelights' ) => 'n',
					__( 'North-East', 'codelights' ) => 'ne',
					__( 'East', 'codelights' ) => 'e',
					__( 'South-East', 'codelights' ) => 'se',
					__( 'South', 'codelights' ) => 's',
					__( 'South-West', 'codelights' ) => 'sw',
					__( 'West', 'codelights' ) => 'w',
					__( 'North-West', 'codelights' ) => 'nw',
				),
				'std' => 'w',
				'group' => __( 'Animation', 'codelights' ),
				'weight' => 70,
			),
			array(
				'param_name' => 'animation_duration',
				'heading' => __( 'Duration', 'codelights' ),
				'type' => 'dropdown',
				'value' => array(
					sprintf( __( '%d ms', 'codelights' ), 100 ) => '100ms',
					sprintf( __( '%d ms', 'codelights' ), 200 ) => '200ms',
					sprintf( __( '%d ms', 'codelights' ), 300 ) => '300ms',
					sprintf( __( '%d ms', 'codelights' ), 400 ) => '400ms',
					sprintf( __( '%d ms', 'codelights' ), 500 ) => '500ms',
					sprintf( __( '%d ms', 'codelights' ), 600 ) => '600ms',
					sprintf( __( '%d ms', 'codelights' ), 700 ) => '700ms',
					sprintf( __( '%d ms', 'codelights' ), 800 ) => '800ms',
					sprintf( __( '%d ms', 'codelights' ), 900 ) => '900ms',
					sprintf( __( '%d ms', 'codelights' ), 1000 ) => '1000ms',
					sprintf( __( '%d ms', 'codelights' ), 1100 ) => '1100ms',
					sprintf( __( '%d ms', 'codelights' ), 1200 ) => '1200ms',
				),
				'std' => '600ms',
				'edit_field_class' => 'vc_col-sm-6 vc_column',
				'group' => __( 'Animation', 'codelights' ),
				'weight' => 60,
			),
			array(
				'param_name' => 'animation_easing',
				'heading' => __( 'Easing', 'codelights' ),
				'type' => 'dropdown',
				'value' => array(
					__( 'Linear', 'codelights' ) => 'linear',
					'easeInOutSine' => 'easeInOutSine',
					'easeInQuad' => 'easeInQuad',
					'easeInOutCirc' => 'easeInOutCirc',
					'easeInBack' => 'easeInBack',
					'easeOutBack' => 'easeOutBack',
					'easeInOutBack' => 'easeInOutBack',
				),
				'std' => 'easeInOutSine',
				'edit_field_class' => 'vc_col-sm-6 vc_column',
				'group' => __( 'Animation', 'codelights' ),
				'weight' => 50,
			),
			/**
			 * General Settings
			 */
			array(
				'param_name' => 'link',
				'heading' => __( 'FlipBox Link', 'codelights' ),
				'type' => 'vc_link',
				'group' => __( 'General Settings', 'codelights' ),
				'weight' => 40,
			),
			array(
				'param_name' => 'width',
				'heading' => __( 'Width', 'codelights' ),
				'type' => 'textfield',
				'std' => '100%',
				'group' => __( 'General Settings', 'codelights' ),
				'weight' => 30,
			),
			array(
				'param_name' => 'height',
				'heading' => __( 'Height', 'codelights' ),
				'description' => __( 'Leave blank to use the maximum side height', 'codelights' ),
				'type' => 'textfield',
				'std' => '',
				'group' => __( 'General Settings', 'codelights' ),
				'weight' => 20,
			),
			array(
				'param_name' => 'el_class',
				'heading' => __( 'Extra class name', 'us' ),
				'description' => __( 'If you wish to style particular content element differently, then use this field to add a class name and then refer to it in your css file.', 'us' ),
				'type' => 'textfield',
				'group' => __( 'General Settings', 'codelights' ),
				'weight' => 10,
			),
		),
	),

);
